# Generated by Django 3.1.7 on 2022-06-04 08:32

import Tienda.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'CategoryProd',
                'verbose_name_plural': 'CategoriesProd',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Tienda.models.product_directory_path)),
                ('description', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('categories', models.ManyToManyField(to='Tienda.CategoryProd')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('idSale', models.AutoField(primary_key=True, serialize=False)),
                ('shippingAddress', models.TextField(blank=True, verbose_name='Shipping address')),
                ('billingAddress', models.TextField(blank=True, verbose_name='Billing address')),
                ('ref', models.CharField(help_text='A order reference.', max_length=128, verbose_name='Reference')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('codeProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.product')),
                ('idSale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.sale')),
            ],
            options={
                'verbose_name': 'SaleItem',
                'verbose_name_plural': 'SaleItems',
            },
        ),
    ]
