# Generated by Django 3.1.7 on 2022-05-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='AppTienda')),
                ('descripcion', models.CharField(max_length=150)),
                ('precio', models.FloatField()),
                ('categorias', models.ManyToManyField(to='Tienda.CategoriaProd')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
