# Generated by Django 3.1.7 on 2022-05-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
