# Generated by Django 3.1.7 on 2022-05-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSale', models.PositiveIntegerField()),
                ('shippingAddress', models.TextField(blank=True, verbose_name='Shipping address')),
                ('billingAddress', models.TextField(blank=True, verbose_name='Billing address')),
                ('ref', models.CharField(help_text='A order reference.', max_length=128, verbose_name='Reference')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
            ],
        ),
    ]
