# Generated by Django 3.1.7 on 2022-06-01 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_auto_20220531_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSale', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('codeProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.product')),
            ],
            options={
                'verbose_name': 'SaleItem',
                'verbose_name_plural': 'SaleItems',
            },
        ),
    ]
